#!/bin/sh

# Create directory if needed
cd ~
mkdir -p covid19
cd covid19

# Generate data
covid19-data

# Setup needed variables
DATAGOUV_API="https://www.data.gouv.fr/api/1"
FILE_PATH="${HOME}/covid19/covid19.csv"
DATASET="5e689ada634f4177317e4820"
RESOURCE="fa9b8fc8-35d5-4e24-90eb-9abe586b0fa5"
# https://www.data.gouv.fr/fr/admin/dataset/5e689ada634f4177317e4820/

# Upload the csv
curl -H "Accept:application/json" \
     -H "X-Api-Key:$DATAGOUV_API_TOKEN" \
     -F "file=@${FILE_PATH}" \
     -X POST $DATAGOUV_API/datasets/$DATASET/resources/$RESOURCE/upload/
